return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 11,
  nextobjectid = 22,
  backgroundcolor = { 0, 0, 0 },
  properties = {
    ["music"] = "castletown"
  },
  tilesets = {
    {
      name = "castle_throneroom",
      firstgid = 1,
      filename = "../../tilesets/castle_throneroom.tsx",
      exportfilename = "../../tilesets/castle_throneroom.lua"
    },
    {
      name = "castle_dojo",
      firstgid = 91,
      filename = "../../tilesets/castle_dojo.tsx"
    },
    {
      name = "castle_town_bg",
      firstgid = 235,
      filename = "../../tilesets/castle_town_bg.tsx",
      exportfilename = "../../tilesets/castle_town_bg.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "tiles_bed",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 15,
      offsety = -10,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 52, 53, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 57, 58, 59, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 63, 64, 65, 66, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 69, 70, 71, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 2,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0,
        0, 0, 116, 117, 117, 117, 117, 117, 117, 117, 117, 117, 117, 118, 0, 0,
        0, 0, 128, 0, 0, 0, 195, 196, 196, 197, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 207, 208, 208, 209, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 219, 220, 220, 221, 0, 0, 0, 130, 0, 0,
        0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 130, 0, 0,
        0, 0, 140, 141, 141, 141, 141, 214, 215, 205, 205, 205, 205, 216, 0, 0,
        0, 0, 0, 0, 0, 113, 114, 226, 227, 137, 138, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 125, 126, 226, 227, 149, 150, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 640,
          height = 164,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 119,
          y = 260,
          width = 68,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 294,
          width = 35,
          height = 102,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 187,
          y = 308,
          width = 26,
          height = 58,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 187,
          y = 366,
          width = 2,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 187,
          y = 294,
          width = 2,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 189,
          y = 298,
          width = 16,
          height = 10,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 164,
          width = 84,
          height = 316,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 396,
          width = 200,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 556,
          y = 164,
          width = 84,
          height = 316,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 356,
          y = 396,
          width = 200,
          height = 84,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 12,
          name = "entry",
          type = "",
          shape = "point",
          x = 319,
          y = 453,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "spawn",
          type = "",
          shape = "point",
          x = 319,
          y = 453,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "objects_decor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 192,
          width = 160,
          height = 80,
          rotation = 0,
          gid = 271,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 115,
          y = 64,
          width = 80,
          height = 34,
          rotation = 0,
          gid = 272,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 79,
          y = 278,
          width = 123,
          height = 122,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a bed for three people,[wait:5] or one three-headed person.)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "collision_decor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 84,
          y = 115,
          width = 160,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 13,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 460,
          width = 80,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "castle_town/area_2",
            ["marker"] = "entry_dojo"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_fx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 21,
          name = "dojo_fx",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 640,
          height = 480,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
