return {
  version = "1.11",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 16,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 17,
  nextobjectid = 42,
  backgroundcolor = { 0, 0, 0 },
  properties = {
    ["music"] = "castletown"
  },
  tilesets = {
    {
      name = "castle_cardcastle",
      firstgid = 1,
      filename = "../../tilesets/castle_cardcastle.tsx",
      exportfilename = "../../tilesets/castle_cardcastle.lua"
    },
    {
      name = "castle_throneroom",
      firstgid = 145,
      filename = "../../tilesets/castle_throneroom.tsx",
      exportfilename = "../../tilesets/castle_throneroom.lua"
    },
    {
      name = "castle_town_bg",
      firstgid = 235,
      filename = "../../tilesets/castle_town_bg.tsx",
      exportfilename = "../../tilesets/castle_town_bg.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 16,
      height = 12,
      id = 1,
      name = "tiles",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 27, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 3, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 0,
        0, 0, 0, 0, 13, 14, 14, 5, 4, 14, 14, 15, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 10,
      name = "objects_tiles_deco",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 220,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 221,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 150,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 222,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 226,
          visible = true,
          properties = {}
        },
        {
          id = 6,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 228,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 234,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "",
          type = "",
          shape = "rectangle",
          x = 180,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 232,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 230,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 233,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "",
          shape = "rectangle",
          x = 220,
          y = 190,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 227,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "",
          type = "",
          shape = "rectangle",
          x = 390,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 179,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "",
          shape = "rectangle",
          x = 430,
          y = 180,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 180,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "",
          type = "",
          shape = "rectangle",
          x = 410,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 186,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "",
          shape = "rectangle",
          x = 210,
          y = 70,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 18,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 240,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "",
          type = "",
          shape = "rectangle",
          x = 370,
          y = 300,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 270,
          y = 280,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 190,
          y = 290,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 174,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "collision",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 80,
          width = 360,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "",
          type = "",
          shape = "rectangle",
          x = 480,
          y = 120,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 320,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 26,
          name = "",
          type = "",
          shape = "rectangle",
          x = 360,
          y = 360,
          width = 40,
          height = 120,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 27,
          name = "",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 320,
          width = 40,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 320,
          width = 120,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 120,
          y = 80,
          width = 40,
          height = 240,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 120,
          width = 130,
          height = 100,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 19,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 300,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_town/lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 20,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 340,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_town/lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 21,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 380,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_town/lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 22,
          name = "npc",
          type = "",
          shape = "rectangle",
          x = 420,
          y = 90,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 286,
          visible = true,
          properties = {
            ["actor"] = "castle_town/lancerpainting",
            ["script"] = "castle_room_lancer_painting"
          }
        },
        {
          id = 32,
          name = "transition",
          type = "",
          shape = "rectangle",
          x = 280,
          y = 480,
          width = 80,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {
            ["map"] = "castle_2f",
            ["marker"] = "entry_lancer",
            ["sound"] = "reverse_splat"
          }
        },
        {
          id = 35,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 110,
          width = 130,
          height = 110,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a bikeless bed.)"
          }
        },
        {
          id = 36,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 390,
          y = 150,
          width = 60,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {
            ["cutscene"] = "castle_room_lancer.music_player"
          }
        },
        {
          id = 37,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 420,
          y = 210,
          width = 20,
          height = 30,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's some kind of digging implement.)"
          }
        },
        {
          id = 38,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 370,
          y = 270,
          width = 30,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (There's salsa buried in the ground here.)"
          }
        },
        {
          id = 39,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 210,
          width = 30,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a hole.[wait:5] Presumably dug for fun.)"
          }
        },
        {
          id = 40,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 270,
          y = 250,
          width = 30,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["text"] = "* (It's a hole made recreationally.)"
          }
        },
        {
          id = 41,
          name = "interactable",
          type = "",
          shape = "rectangle",
          x = 190,
          y = 260,
          width = 30,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {
            ["text1"] = "* (You found 20 Rupys in the hole!)",
            ["text2"] = "* (Unfortunately,[wait:5] that's not a useful currency here...)"
          }
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "markers",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 33,
          name = "entry",
          type = "",
          shape = "point",
          x = 326,
          y = 435,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "spawn",
          type = "",
          shape = "point",
          x = 319,
          y = 464,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
